CREATE TABLE IF NOT EXISTS news (
    id SERIAL PRIMARY KEY,
    telegram_url VARCHAR(255) UNIQUE NOT NULL,
    news_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);